spring:
    datasource:
        url: jdbc:mysql://47.106.241.182:3306/fidle?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ZCX
        password: 321123klklkl
    thymeleaf:
        cache: false
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
mybatis:
    type-aliases-package: com.example.fidledemo.DO , com.example.fidledemo.BO
    mapper-locations: classpath*:com/example/fidledemo/dao/*.xml

server:
    port: 8083
imageHost:
    url: http://47.106.241.182:8083/fidle/
    path: /usr/local/apache-tomcat-9.0.44/webapps/fidle/
size: 10


